--------------------------------------------------------
--  EJECUTAR EN SYSTEM
--------------------------------------------------------
--TABLE SPACE DATA 
CREATE TABLESPACE LAB1_DATA DATAFILE 'C:\Oracle18c\oradata\XE\LAB1_DATA.dbf' SIZE 52M   ONLINE;
-- TABLE SPACE TEMP
CREATE TEMPORARY TABLESPACE LAB1_TEMP TEMPFILE 'C:\Oracle18c\oradata\XE\LAB1_TEMP.dbf' SIZE 18M  AUTOEXTEND ON ;
--CREAR UN SCHEMA NUEVO 
  
alter session set "_ORACLE_SCRIPT" =true;   
CREATE USER LAB IDENTIFIED BY root
       DEFAULT TABLESPACE LAB1_DATA
       TEMPORARY TABLESPACE  LAB1_TEMP;
       
       
GRANT RESOURCE TO LAB; 
GRANT CONNECT TO LAB;
GRANT ALL PRIVILEGES TO LAB; 

--------------------------------------------------------
--  EJECUTAR EN EL NUEVO ESQUEMA
--------------------------------------------------------

CREATE TABLE CARRERAS(
    CODIGO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100),
    TITULO VARCHAR2(100),
    CONSTRAINT PK_COD_CARRERAS PRIMARY KEY (CODIGO)    
);


CREATE TABLE CURSOS(
    CODIGO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100),
    CREDITOS NUMBER(10),
    HORAS NUMBER(10),
    CONSTRAINT PK_COD_CURSOS PRIMARY KEY(CODIGO)
);


CREATE TABLE CARRERACURSOS(
    CODCARRERA NUMBER(10) NOT NULL,
    CODCURSOS NUMBER(10) NOT NULL,
    ANO VARCHAR2(100),
    CICLO VARCHAR2(100)
);
ALTER TABLE CARRERACURSOS ADD CONSTRAINT FK_COD_CARRERAS FOREIGN  KEY(CODCARRERA) REFERENCES CARRERAS(CODIGO);
ALTER TABLE CARRERACURSOS ADD CONSTRAINT FK_COD_CURSOS FOREIGN  KEY(CODCURSOS) REFERENCES CURSOS(CODIGO);

--------------------------------------------------------
--  DDL for Procedure SP_INSERTACARRERA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_INSERTACARRERA" (
p_CODIGO IN NUMBER,
p_NOMBRE IN VARCHAR2,
p_TITULO IN VARCHAR2)
IS
BEGIN
INSERT INTO CARRERAS (CODIGO, NOMBRE, TITULO)
VALUES (p_CODIGO, p_NOMBRE, p_TITULO);
END SP_INSERTACARRERA;

--------------------------------------------------------
--  DDL for Procedure SP_INSERTACURSOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_INSERTACURSOS" (
p_CODIGO IN NUMBER,
p_NOMBRE IN VARCHAR2,
p_CREDITOS IN NUMBER,
p_HORAS IN NUMBER)
IS
BEGIN
INSERT INTO CURSOS (CODIGO, NOMBRE, CREDITOS, HORAS)
VALUES (p_CODIGO, p_NOMBRE, p_CREDITOS, p_HORAS);
END SP_INSERTACURSOS;

--------------------------------------------------------
--  DDL for Procedure SP_INSERTACARRERACURSOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_INSERTACARRERACURSOS" (
p_CODCARRERA IN NUMBER,
p_CODCURSOS IN VARCHAR2,
p_ANO IN NUMBER,
p_CICLO IN NUMBER)
IS
BEGIN
INSERT INTO CARRERACURSOS (CODCARRERA, CODCURSOS, ANO, CICLO)
VALUES (p_CODCARRERA, p_CODCURSOS, p_ANO, p_CICLO);
END SP_INSERTACARRERACURSOS;

--------------------------------------------------------
--  DDL for Procedure SP_UPDATECARRERA
--------------------------------------------------------

CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_UPDATECARRERA" (
p_CODIGO IN CARRERAS.CODIGO%TYPE,
p_NOMBRE IN CARRERAS.NOMBRE%TYPE,
p_TITULO IN CARRERAS.TITULO%TYPE)
IS
BEGIN
UPDATE CARRERAS SET
NOMBRE = p_NOMBRE,
TITULO = p_TITULO
WHERE CODIGO = p_CODIGO;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_UPDATECARRERA;

--------------------------------------------------------
--  DDL for Procedure SP_UPDATECURSOS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_UPDATECURSOS" (
p_CODIGO IN CURSOS.CODIGO%TYPE,
p_NOMBRE IN CURSOS.NOMBRE%TYPE,
p_CREDITOS IN CURSOS.CREDITOS%TYPE,
p_HORAS IN CURSOS.HORAS%TYPE)
IS
BEGIN
UPDATE CURSOS SET
NOMBRE = p_NOMBRE,
CREDITOS = p_CREDITOS,
HORAS = p_HORAS
WHERE CODIGO = p_CODIGO;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_UPDATECURSOS;

--------------------------------------------------------
--  DDL for Procedure SP_UPDATECARRERACURSOS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_UPDATECARRERACURSOS" (
p_CODCARRERA IN CARRERACURSOS.CODCARRERA%TYPE,
p_CODCURSOS IN CARRERACURSOS.CODCURSOS%TYPE,
p_ANO IN CARRERACURSOS.ANO%TYPE,
p_CICLO IN CARRERACURSOS.CICLO%TYPE)
IS
BEGIN
UPDATE CARRERACURSOS SET
ANO = p_ANO,
CICLO = p_CICLO
WHERE CODCARRERA = p_CODCARRERA AND CODCURSOS = p_CODCURSOS;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_UPDATECARRERACURSOS;

--------------------------------------------------------
--  DDL for Procedure SP_DELETECARRERAS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_DELETECARRERAS" 
 (p_CODIGO IN CARRERAS.CODIGO%TYPE)
IS
BEGIN
DELETE FROM CARRERAS WHERE CODIGO = p_CODIGO;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_DELETECARRERAS;

--------------------------------------------------------
--  DDL for Procedure SP_DELETECURSOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_DELETECURSOS" 
 (p_CODIGO IN CURSOS.CODIGO%TYPE)
IS
BEGIN
DELETE FROM CARRERAS WHERE CODIGO = p_CODIGO;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_DELETECURSOS;

--------------------------------------------------------
--  DDL for Procedure SP_DELETECARRERACURSOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SP_DELETECARRERACURSOS" 
 (p_CODCARRERA IN CARRERACURSOS.CODCARRERA%TYPE,
  p_CODCURSOS IN CARRERACURSOS.CODCURSOS%TYPE)
IS
BEGIN
DELETE FROM CARRERACURSOS WHERE CODCARRERA = p_CODCARRERA AND CODCURSOS = p_CODCURSOS;
EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_DELETECARRERACURSOS;

